# Generated by Django 5.2 on 2026-02-03 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_achievement_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.BigIntegerField(default=0)),
                ('multiplier', models.FloatField(default=1.5)),
                ('target_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='reward_apples',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='reward_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='reward_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='buff_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='buff_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='event_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='event_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserUpgradeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.upgradecard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'card')},
            },
        ),
    ]
