# Generated by Django 5.2 on 2026-02-03 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_upgradecard_achievement_reward_apples_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamestate",
            name="last_tick",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
