# Generated by Django 5.2 on 2026-02-03 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamestate_last_tick_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '成就', 'verbose_name_plural': '成就'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': '建筑', 'verbose_name_plural': '建筑'},
        ),
        migrations.AlterModelOptions(
            name='gamestate',
            options={'verbose_name': '玩家状态', 'verbose_name_plural': '玩家状态'},
        ),
        migrations.AlterModelOptions(
            name='upgradecard',
            options={'verbose_name': '升级卡', 'verbose_name_plural': '升级卡'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': '用户成就', 'verbose_name_plural': '用户成就'},
        ),
        migrations.AlterModelOptions(
            name='userbuilding',
            options={'verbose_name': '用户建筑', 'verbose_name_plural': '用户建筑'},
        ),
        migrations.AlterModelOptions(
            name='userupgradecard',
            options={'verbose_name': '用户升级卡', 'verbose_name_plural': '用户升级卡'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='building_key',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='目标建筑键'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='键名'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='kind',
            field=models.CharField(max_length=30, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_apples',
            field=models.BigIntegerField(default=0, verbose_name='奖励点数'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_multiplier',
            field=models.FloatField(default=1.0, verbose_name='奖励倍率'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_seconds',
            field=models.IntegerField(default=0, verbose_name='奖励时长(秒)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='rule',
            field=models.CharField(max_length=200, verbose_name='规则描述'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='threshold',
            field=models.BigIntegerField(verbose_name='达成阈值'),
        ),
        migrations.AlterField(
            model_name='building',
            name='base_per_click',
            field=models.FloatField(default=0.0, verbose_name='每点击产出'),
        ),
        migrations.AlterField(
            model_name='building',
            name='base_per_second',
            field=models.FloatField(default=0.0, verbose_name='每秒产出'),
        ),
        migrations.AlterField(
            model_name='building',
            name='base_price',
            field=models.BigIntegerField(verbose_name='基础价格'),
        ),
        migrations.AlterField(
            model_name='building',
            name='flavor',
            field=models.CharField(max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='building',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='键名'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='building',
            name='price_growth',
            field=models.FloatField(default=1.15, verbose_name='价格增长倍率'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='apples',
            field=models.BigIntegerField(default=0, verbose_name='当前点数'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='apples_total',
            field=models.BigIntegerField(default=0, verbose_name='累计点数'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='buff_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='加成结束时间'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='buff_multiplier',
            field=models.FloatField(default=1.0, verbose_name='加成倍率'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='clicks',
            field=models.BigIntegerField(default=0, verbose_name='点击次数'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='event_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='事件过期时间'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='event_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='事件ID'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='event_multiplier',
            field=models.FloatField(default=1.0, verbose_name='事件倍率'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次事件时间'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='last_tick',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次结算时间'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='upgrade_level',
            field=models.IntegerField(default=0, verbose_name='成长等级'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='upgradecard',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='upgradecard',
            name='description',
            field=models.CharField(max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='upgradecard',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='键名'),
        ),
        migrations.AlterField(
            model_name='upgradecard',
            name='multiplier',
            field=models.FloatField(default=1.5, verbose_name='倍率'),
        ),
        migrations.AlterField(
            model_name='upgradecard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='upgradecard',
            name='target_key',
            field=models.CharField(max_length=50, verbose_name='目标建筑键'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.achievement', verbose_name='成就'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='unlocked',
            field=models.BooleanField(default=False, verbose_name='是否解锁'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userbuilding',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='拥有数量'),
        ),
        migrations.AlterField(
            model_name='userbuilding',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.building', verbose_name='建筑'),
        ),
        migrations.AlterField(
            model_name='userbuilding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userupgradecard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.upgradecard', verbose_name='升级卡'),
        ),
        migrations.AlterField(
            model_name='userupgradecard',
            name='owned',
            field=models.BooleanField(default=False, verbose_name='是否拥有'),
        ),
        migrations.AlterField(
            model_name='userupgradecard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
